export const JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET';
export const JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';

export const jwtConstantsTemplateValue = {
    JWT_ACCESS_SECRET:
        'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
    JWT_REFRESH_SECRET:
        'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};
